### ISSUE TITLE
Revision History - Part II

### ISSUE THREAD

**Issue by benjore** [unfoldingWord-dev/design#156]
- [x] Remove the Frowny Face & "Sorry"
- [x] Each revision needs to show not only which tool was used, but what check the edit was performed on. 
  - [x] e.g. 1. tN, 2. Metonymy, 3. "our blessed hope"
  - [x] e.g. 1. tW, 2. Apostle, apostleship, 3. "apostle" 
  - [x] 1. tool, 2. category, 3. check
- [x] When only one revision is being shown, the text should only be black (no diff)
- [ ] Figure out how the diffs work (is one the base and the second shows all the diffs? Does each show half of the revisions e.g. one show red and the other show green.)
- [ ] Figure out how to show diffs between two non-current revisions. 
- [x] Add comments to the historical list
  - [x] Figure out a way to hide/not show the comments
  - [x] Show the check that the comments were made on (see above)
- [x] Primary focus should be the compared verses, not the "menu" of historical edits. (e.g. make the compare bigger)

**Comment by Thajny** [comment]
![revision history compare 2](https://cloud.githubusercontent.com/assets/21183377/26076848/b824a0b8-397f-11e7-963a-368c2428c918.png)
![revision history compare 3](https://cloud.githubusercontent.com/assets/21183377/26076847/b821f606-397f-11e7-8e12-19fe3a3ef7be.png)
![revision history empty state](https://cloud.githubusercontent.com/assets/21183377/26076846/b821eac6-397f-11e7-8d3c-f85a20124ed9.png)

**Comment by Thajny** [comment]
![revision history default](https://cloud.githubusercontent.com/assets/21183377/26076861/c85b509e-397f-11e7-8b2d-2ae8ffc86382.png)
![revision history compare 1](https://cloud.githubusercontent.com/assets/21183377/26076865/cc3075aa-397f-11e7-9f88-167b469f4bf4.png)

**Comment by Thajny** [comment]
![revision history compare 3](https://cloud.githubusercontent.com/assets/21183377/26313471/a3d03e32-3ed0-11e7-9299-c40d01c0e0a1.png)
![revision history compare 4](https://cloud.githubusercontent.com/assets/21183377/26313466/a32f2740-3ed0-11e7-9c19-53f7c9b61dbd.png)
![revision history compare 5](https://cloud.githubusercontent.com/assets/21183377/26313467/a3435dfa-3ed0-11e7-9c5c-fc15622b574c.png)
![revision history compare 6](https://cloud.githubusercontent.com/assets/21183377/26313468/a356b666-3ed0-11e7-9d4d-38e549059fd6.png)
![revision history empty state](https://cloud.githubusercontent.com/assets/21183377/26313469/a35764c6-3ed0-11e7-8437-cd1dcf04d8e8.png)

**Comment by Thajny** [comment]
![revision history compare 3](https://cloud.githubusercontent.com/assets/21183377/26313731/679fecc2-3ed1-11e7-9bf7-81377b98a1c6.png)
![revision history compare 4](https://cloud.githubusercontent.com/assets/21183377/26313732/67b5b868-3ed1-11e7-90dd-5b20b5774f02.png)
![revision history compare 5](https://cloud.githubusercontent.com/assets/21183377/26313734/67d2c066-3ed1-11e7-8eaf-84a8dadbb65c.png)
![revision history compare 6](https://cloud.githubusercontent.com/assets/21183377/26313735/690a75fa-3ed1-11e7-845d-89e1bdd51f1f.png)
![revision history empty state](https://cloud.githubusercontent.com/assets/21183377/26313733/67cf5340-3ed1-11e7-9038-99db2f3e0090.png)

**Comment by Thajny** [comment]
**Notes:**
- A list of all saved revisions on a "per-verse" level should be displayed on the left as one card with a list. This is because all of the information shown is similar, and as such can and should be displayed as one card.

- In the current design, the most current selected revision will always show what was added between it, and the other selected revision.

- Only one tickbox per collumn can be selected. These tickboxes are color coded to match the cards on the right.

- By default, no revision is selected and the 2 cards on the left are slightly grayed out and display instructions to the user to "select a revision to compare."

- Additionally, the list can be sorted by: User, Tool, and Date.

- The user can filter out comments from the revision history as well. Comments made may not have anything to do with the current check, and so should not be shown inline with edits.

- Meta data included with the revision is stored in the cards on the right and by default are hidden.
 
- The user can click "show meta data" to expand the card to view it.
